---
title: "Reinventing Jakob Junis Using Q-Learning"
author: "Logan Mottley"
date: "5/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(broom)
library(ReinforcementLearning)
library(ggthemr)
theme_set(theme_minimal())


jake_junis <- read.csv("Desktop/Data/Statcast Data (2015-2019).csv") %>%
  filter(pitcher == 596001, 
         game_year >= 2018) %>%
  select(game_year, game_date, inning_topbot, 
         inning, player_name, batter,
         pitch_type, events, description, 
         bb_type, pitch_number, strikes, balls) 

##### NOTE: The data munging code is pretty ugly, theres certainly a more efficient way to do it, but this worked for me. 

```

Junis 2018 Data 
```{r}

# junis 2018 data
jake_junis_2018 <- jake_junis %>%
  filter(game_year == 2018) %>%
  mutate(at_bat = "", 
         state = "") %>%
  select(-game_year)


# making an at_bat variable 
jake_junis_2018$at_bat <- paste(jake_junis_2018$game_date,
                                      jake_junis_2018$inning_topbot,
                                      jake_junis_2018$inning,
                                      jake_junis_2018$player_name,
                                      sep = "_") 


# making a state variable for all possible non-terminal states
jake_junis_2018$state <- paste(jake_junis_2018$balls,
                                     jake_junis_2018$strikes, 
                                     sep = "-")

# making ground out a seperate terminal state by merging bb_type 'ground_ball' into events column
jake_junis_2018 <- jake_junis_2018 %>%
  mutate(events = ifelse(bb_type == "ground_ball", "ground_ball", as.character(events)))


# arranged dataset 
jake_junis_2018 <- jake_junis_2018 %>%
    select(at_bat, pitch_type, events,
           description, pitch_number, 
           state) %>%
  group_by(at_bat) %>%
  arrange(at_bat, pitch_number) 

# inlcuding terminal states into state column 
jake_junis_2018$events <- as.character(jake_junis_2018$events)

# renaming all terminal states
jake_junis_2018$events[jake_junis_2018$events == "strikeout"]  <- "SO" 
jake_junis_2018$events[jake_junis_2018$events == "ground_ball"]  <- "GO" 
jake_junis_2018$events[jake_junis_2018$events == "field_out"]  <- "O" 
jake_junis_2018$events[jake_junis_2018$events == "force_out"]  <- "FO" # Force Out
jake_junis_2018$events[jake_junis_2018$events == "sac_bunt"]  <- "BO"  # Bunt Out
jake_junis_2018$events[jake_junis_2018$events == "double_play"]  <- "DP" # Double Play 
jake_junis_2018$events[jake_junis_2018$events == "grounded_into_double_play"]  <- "GIDP" # GIDP
jake_junis_2018$events[jake_junis_2018$events == "pickoff_caught_stealing_home"]  <- "PICK" # Pick
jake_junis_2018$events[jake_junis_2018$events == "caught_stealing_home"]  <- "CS" # CS
jake_junis_2018$events[jake_junis_2018$events == "strikeout_double_play"]  <- "DP" # Double play
jake_junis_2018$events[jake_junis_2018$events == "field_error"]  <- "E" # Error 
jake_junis_2018$events[jake_junis_2018$events == "caught_stealing_2b"]  <- "CS" # CS 
jake_junis_2018$events[jake_junis_2018$events == "sac_fly"]  <- "SACFLY" # Sac fly
jake_junis_2018$events[jake_junis_2018$events == "single"]  <- "S" 
jake_junis_2018$events[jake_junis_2018$events == "double"]  <- "D" 
jake_junis_2018$events[jake_junis_2018$events == "triple"]  <- "T" 
jake_junis_2018$events[jake_junis_2018$events == "home_run"]  <- "HR" 
jake_junis_2018$events[jake_junis_2018$events == "walk"]  <- "W" 
jake_junis_2018$events[jake_junis_2018$events == "hit_by_pitch"]  <- "W" 


# merging all terminal states into 'events' column
jake_junis_2018$events <- ifelse(is.na(jake_junis_2018$events), 
                                 jake_junis_2018$state, 
                                 jake_junis_2018$events)


# renaming 'events' column to 'next_state'
names(jake_junis_2018)[3] <- "next_state"

# reordering columns just to help visually and getting rid of description 
# (and temporatily pitch_number)
jake_junis_2018 <- jake_junis_2018 %>%
  select(at_bat, pitch_type, state, 
         next_state)

# removing initial state '0-0' from 'next_state' because you cant end on an initial state 
# I'm using X as a placeholder because I can't keep the rows of a value that I removed
jake_junis_2018$next_state[jake_junis_2018$next_state == "0-0"]  <- "X" 

# removing all counts associated with terminal states with the exception of at_bats that end in an initial state (first pitch terminal state), again replacing them with X and also removing the 'pitch_number' column
jake_junis_2018 <- jake_junis_2018 %>%
  group_by(at_bat) %>%
  mutate(pitch_number = row_number()!=n()|n()==1, 
         state = ifelse(pitch_number == FALSE, 'X', state)) 

# view that there are the same number of X's in each column 
table(jake_junis_2018$state)
table(jake_junis_2018$next_state)

# turning description into an action column 
# (five actions corresponding with each pitch type, "CH" "CU" "FF" "SI" "SL")
jake_junis_2018$pitch_type <- as.character(jake_junis_2018$pitch_type)

# renaming description columnn
jake_junis_2018$pitch_type[jake_junis_2018$pitch_type == "FF"]  <- "FF" 
jake_junis_2018$pitch_type[jake_junis_2018$pitch_type == "CU"]  <- "CU" 
jake_junis_2018$pitch_type[jake_junis_2018$pitch_type == "SI"]  <- "SI" 
jake_junis_2018$pitch_type[jake_junis_2018$pitch_type == "SL"]  <- "SL" 
jake_junis_2018$pitch_type[jake_junis_2018$pitch_type == "CH"]  <- "CH" 


# renaming 'pitch_type' column to 'action'
names(jake_junis_2018)[2] <- "action"

# making a 'reward' column  
jake_junis_2018 <- jake_junis_2018 %>%
  mutate(reward = next_state)

# changing terminal state reward column values to specific rewards
jake_junis_2018$reward[jake_junis_2018$reward == "FO"] <- 0.58
jake_junis_2018$reward[jake_junis_2018$reward == "BO"] <- 0.23	
jake_junis_2018$reward[jake_junis_2018$reward == "DP"] <- 1.06	
jake_junis_2018$reward[jake_junis_2018$reward == "GIDP"] <- 0.85
jake_junis_2018$reward[jake_junis_2018$reward == "PICK"] <- 0.49
jake_junis_2018$reward[jake_junis_2018$reward == "CS"] <- 0.45
jake_junis_2018$reward[jake_junis_2018$reward == "E"] <- 0.456 # average of all positive rewards
jake_junis_2018$reward[jake_junis_2018$reward == "SACFLY"] <- 0.08
jake_junis_2018$reward[jake_junis_2018$reward == "GO"] <- 0.24
jake_junis_2018$reward[jake_junis_2018$reward == "SO"] <- 0.30
jake_junis_2018$reward[jake_junis_2018$reward == "O"] <- 0.28
jake_junis_2018$reward[jake_junis_2018$reward == "W"] <- -0.55
jake_junis_2018$reward[jake_junis_2018$reward == "S"] <- -0.70
jake_junis_2018$reward[jake_junis_2018$reward == "D"] <- -1.00
jake_junis_2018$reward[jake_junis_2018$reward == "T"] <- -1.27
jake_junis_2018$reward[jake_junis_2018$reward == "HR"] <- -1.65


# changing non-terminal states to 0's 
jake_junis_2018$reward[jake_junis_2018$reward == "0-0"] <- 0
jake_junis_2018$reward[jake_junis_2018$reward == "1-0"] <- 0
jake_junis_2018$reward[jake_junis_2018$reward == "1-1"] <- 0
jake_junis_2018$reward[jake_junis_2018$reward == "1-2"] <- 0
jake_junis_2018$reward[jake_junis_2018$reward == "2-2"] <- 0
jake_junis_2018$reward[jake_junis_2018$reward == "3-2"] <- 0
jake_junis_2018$reward[jake_junis_2018$reward == "0-1"] <- 0
jake_junis_2018$reward[jake_junis_2018$reward == "0-2"] <- 0
jake_junis_2018$reward[jake_junis_2018$reward == "2-1"] <- 0
jake_junis_2018$reward[jake_junis_2018$reward == "2-0"] <- 0
jake_junis_2018$reward[jake_junis_2018$reward == "3-1"] <- 0
jake_junis_2018$reward[jake_junis_2018$reward == "3-0"] <- 0


# reordering the columns just to help visually 
jake_junis_2018 <- jake_junis_2018 %>%
  select(at_bat, state, action, next_state, reward)


# removing all X's 'state' column 
state_column <- jake_junis_2018 %>%
  select(state) %>%
  filter(state != "X")

# removing all X's 'next_state' column 
next_state_column <- jake_junis_2018 %>%
  select(next_state) %>%
  filter(next_state != "X")

# removing all X's 'reward' column 
reward_column <- jake_junis_2018 %>%
  select(reward) %>%
  filter(reward != "X")

# action column 
action_column <- jake_junis_2018 %>%
  select(reward, action) %>%
  filter(reward != "X") %>%
  select(action)

# binding these columns to make final dataset 
jake_junis_2018 <- data.frame(cbind(state_column$state,
                                          action_column$action, 
                                          next_state_column$next_state,
                                          reward_column$reward))
# renaming columns 
names(jake_junis_2018)[1] <- "state"
names(jake_junis_2018)[2] <- "action"
names(jake_junis_2018)[3] <- "next_state"
names(jake_junis_2018)[4] <- "reward"

```

Policy Evaluation using Q-learning 
```{r}

# defining state and action sets
state <- c("0-0", "0-1", "0-2", "1-0", "1-1", "1-2", 
            "2-0", "2-1", "2-2", "3-0", "3-1", "3-2")
action <- c("CH", "CU", "FF", "SI", "SL")
next_state <- c("0-0", "0-1", "0-2", "1-0", "1-1", "1-2", 
            "2-0", "2-1", "2-2", "3-0", "3-1", "3-2",
            "FO", "BO", "DP", "GIDP", "PICK", "CS", 
            "E", "SACFLY", "GO", "SO", "O", "W", 
            "S", "D", "T", "HR")
reward <- c(0.58, 0.23, 1.06, 0.85, 0.49, 0.45, 0.456, 
            0.08, 0.24, 0.30, 0.28, -0.55, -0.70, -1.00, 
            -1.27, -1.65)

# parameters

# Alpha (learning rate): In order for the agent to learn quickly enough, I found that alpha set at 0.25 was the most justifiable. An alpha set too high will cause the agent to value newly acquired information over old information, whereas an alpha set to 0.25 will cause the agent to value old information slightly more than recently acquired information. Baseball players are famous for having good memories and learning from their mistakes as well as successes. Pitchers usually won't change their approaches significantly based on one bad pitch or one bad game, sometimes not even a bad year, this seems congruent with a learning rate of 0.25.

# Gamma (discount factor): I struggled with this one for a while but found that a higher gamma leads to the agent caring about rewards later in at-bats slightly more than current rewards; this would include quick outs are just as valuable as outs from long at-bats. Most pitchers would favor a quick out over a long at-bat, setting gamma at 0.5 would make the agent reward current rewards over future rewards. 

control <- list(alpha = 0.25, gamma = 0.5)

# adjusting input data structure 
jake_junis_2018$state <- as.character(jake_junis_2018$state)
jake_junis_2018$next_state <- as.character(jake_junis_2018$next_state)
jake_junis_2018$action <- as.character(jake_junis_2018$action)
jake_junis_2018[,4] <- as.numeric(as.character(jake_junis_2018[,4]))

# q-learning algorithm
junis.model <- ReinforcementLearning(data = jake_junis_2018, 
                               s = "state", 
                               a = "action", 
                               r = "reward", 
                               s_new = "next_state", 
                               iter = 1, 
                               verbose = TRUE, 
                               control = control)

# print model 
print(junis.model)

```

Junis 2019 Data
```{r}

# junis 2019 data
jake_junis_2019 <- jake_junis %>%
  filter(game_year == 2019) %>%
  select(game_year, game_date, inning_topbot, 
         inning, batter, pitch_type, 
         events, description, bb_type, 
         pitch_number, strikes, balls) %>%
  mutate(at_bat = "", 
         state = "") %>%
  select(-game_year)

# making an at_bat variable 
jake_junis_2019$at_bat <- paste(jake_junis_2019$game_date,
                                      jake_junis_2019$inning_topbot,
                                      jake_junis_2019$inning,
                                      jake_junis_2019$batter,
                                      sep = "_") 

# making a 'state' variable for all possible non-terminal states
jake_junis_2019$state <- paste(jake_junis_2019$balls,
                                     jake_junis_2019$strikes, 
                                     sep = "-")


# arranged dataset and adding a seperarte batter column 
jake_junis_2019 <- jake_junis_2019 %>%
    select(at_bat, pitch_type, events,
           description, pitch_number, 
           state, batter) %>%
  group_by(at_bat) %>%
  arrange(at_bat, pitch_number) 

# inlcuding terminal states into state column 
jake_junis_2019$events <- as.character(jake_junis_2019$events)

# renaming all terminal states
jake_junis_2019$events[jake_junis_2019$events == "strikeout"]  <- "SO" 
jake_junis_2019$events[jake_junis_2019$events == "ground_ball"]  <- "GO" 
jake_junis_2019$events[jake_junis_2019$events == "field_out"]  <- "O" 
jake_junis_2019$events[jake_junis_2019$events == "force_out"]  <- "FO" # Force Out
jake_junis_2019$events[jake_junis_2019$events == "sac_bunt"]  <- "BO"  # Bunt Out
jake_junis_2019$events[jake_junis_2019$events == "double_play"]  <- "DP" # Double Play 
jake_junis_2019$events[jake_junis_2019$events == "grounded_into_double_play"]  <- "GIDP" # GIDP
jake_junis_2019$events[jake_junis_2019$events == "pickoff_caught_stealing_home"]  <- "PICK" # Pick
jake_junis_2019$events[jake_junis_2019$events == "caught_stealing_home"]  <- "CS" # CS
jake_junis_2019$events[jake_junis_2019$events == "strikeout_double_play"]  <- "DP" # Double play
jake_junis_2019$events[jake_junis_2019$events == "field_error"]  <- "E" # Error 
jake_junis_2019$events[jake_junis_2019$events == "caught_stealing_2b"]  <- "CS" # CS 
jake_junis_2019$events[jake_junis_2019$events == "sac_fly"]  <- "SACFLY" # Sac fly
jake_junis_2019$events[jake_junis_2019$events == "hit_by_pitch"]  <- "W" 
jake_junis_2019$events[jake_junis_2019$events == "catcher_interf"]  <- "W" 
jake_junis_2019$events[jake_junis_2019$events == "fielders_choice_out"]  <- "FC" # FC 
jake_junis_2019$events[jake_junis_2019$events == "caught_stealing_2b"]  <- "CS" # CS
jake_junis_2019$events[jake_junis_2019$events == "single"]  <- "S" 
jake_junis_2019$events[jake_junis_2019$events == "double"]  <- "D" 
jake_junis_2019$events[jake_junis_2019$events == "triple"]  <- "T" 
jake_junis_2019$events[jake_junis_2019$events == "home_run"]  <- "HR" 
jake_junis_2019$events[jake_junis_2019$events == "walk"]  <- "W" 


# merging all terminal states into 'events' column
jake_junis_2019$events <- ifelse(is.na(jake_junis_2019$events), 
                                 jake_junis_2019$state, 
                                 jake_junis_2019$events)


# renaming 'events' column to 'next_state'
names(jake_junis_2019)[3] <- "next_state"

# turning description into an swing column (two action u = swing, u = stand)
jake_junis_2019$description <- as.character(jake_junis_2019$description)

# renaming description columnn
jake_junis_2019$description[jake_junis_2019$description == "ball"]  <- "0" 
jake_junis_2019$description[jake_junis_2019$description == "called_strike"]  <- "0" 
jake_junis_2019$description[jake_junis_2019$description == "hit_by_pitch"]  <- "0" 
jake_junis_2019$description[jake_junis_2019$description == "blocked_ball"]  <- "0" 
jake_junis_2019$description[jake_junis_2019$description == "ball"]  <- "0" 
jake_junis_2019$description[jake_junis_2019$description == "foul_bunt"]  <- "1"
jake_junis_2019$description[jake_junis_2019$description == "hit_into_play_no_out"]  <- "1" 
jake_junis_2019$description[jake_junis_2019$description == "foul_tip"]  <- "1" 
jake_junis_2019$description[jake_junis_2019$description == "swinging_strike"]  <- "1" 
jake_junis_2019$description[jake_junis_2019$description == "hit_into_play"]  <- "1" 
jake_junis_2019$description[jake_junis_2019$description == "swinging_strike_blocked"]  <- "1" 
jake_junis_2019$description[jake_junis_2019$description == "hit_into_play_score"]  <- "1" 
jake_junis_2019$description[jake_junis_2019$description == "foul"]  <- "1" 

# renaming 'description' column to 'swing'
names(jake_junis_2019)[4] <- "swing"

# reordering columns just to help visually
# (and temporatily pitch_number)
jake_junis_2019 <- jake_junis_2019 %>%
  select(at_bat, pitch_type, state, 
         next_state, batter, swing)

# removing initial state '0-0' from 'next_state' because you cant end on an initial state 
# I'm using X as a placeholder because it wont let me keeo the rows of a value that I removed
jake_junis_2019$next_state[jake_junis_2019$next_state == "0-0"]  <- "X" 

# removing all counts associated with terminal states with the exception of at_bats that end in an initial state (first pitch terminal state), again replacing them with X
# also removing the 'pitch_number' column
jake_junis_2019 <- jake_junis_2019 %>%
  group_by(at_bat) %>%
  mutate(pitch_number = row_number()!=n()|n()==1, 
         state = ifelse(pitch_number == FALSE, 'X', state))
  

# turning description into an action column 
# (five actions corresponding with each pitch type, "CH" "CU" "FF" "SI" "SL")
jake_junis_2019$pitch_type <- as.character(jake_junis_2019$pitch_type)

# renaming description columnn
jake_junis_2019$pitch_type[jake_junis_2019$pitch_type == "FF"]  <- "FF" 
jake_junis_2019$pitch_type[jake_junis_2019$pitch_type == "CU"]  <- "CU" 
jake_junis_2019$pitch_type[jake_junis_2019$pitch_type == "SI"]  <- "SI" 
jake_junis_2019$pitch_type[jake_junis_2019$pitch_type == "SL"]  <- "SL" 
jake_junis_2019$pitch_type[jake_junis_2019$pitch_type == "CH"]  <- "CH" 

# renaming 'pitch_type' column to 'action'
names(jake_junis_2019)[2] <- "action"

# making a 'reward' column  
jake_junis_2019 <- jake_junis_2019 %>%
  mutate(reward = next_state)

# changing terminal state reward column values to specific rewards
jake_junis_2019$reward[jake_junis_2019$reward == "FO"] <- 0.58
jake_junis_2019$reward[jake_junis_2019$reward == "BO"] <- 0.23	
jake_junis_2019$reward[jake_junis_2019$reward == "DP"] <- 1.06	
jake_junis_2019$reward[jake_junis_2019$reward == "GIDP"] <- 0.85
jake_junis_2019$reward[jake_junis_2019$reward == "PICK"] <- 0.49
jake_junis_2019$reward[jake_junis_2019$reward == "CS"] <- 0.45
jake_junis_2019$reward[jake_junis_2019$reward == "E"] <- 0.456 # average of all positive rewards
jake_junis_2019$reward[jake_junis_2019$reward == "SACFLY"] <- 0.08
jake_junis_2019$reward[jake_junis_2019$reward == "GO"] <- 0.24
jake_junis_2019$reward[jake_junis_2019$reward == "SO"] <- 0.30
jake_junis_2019$reward[jake_junis_2019$reward == "O"] <- 0.28
jake_junis_2019$reward[jake_junis_2019$reward == "FC"] <- 0.16
jake_junis_2019$reward[jake_junis_2019$reward == "W"] <- -0.55
jake_junis_2019$reward[jake_junis_2019$reward == "S"] <- -0.70
jake_junis_2019$reward[jake_junis_2019$reward == "D"] <- -1.00
jake_junis_2019$reward[jake_junis_2019$reward == "T"] <- -1.27
jake_junis_2019$reward[jake_junis_2019$reward == "HR"] <- -1.65

# changing non-terminal states to 0's 
jake_junis_2019$reward[jake_junis_2019$reward == "0-0"] <- 0
jake_junis_2019$reward[jake_junis_2019$reward == "1-0"] <- 0
jake_junis_2019$reward[jake_junis_2019$reward == "1-1"] <- 0
jake_junis_2019$reward[jake_junis_2019$reward == "1-2"] <- 0
jake_junis_2019$reward[jake_junis_2019$reward == "2-2"] <- 0
jake_junis_2019$reward[jake_junis_2019$reward == "3-2"] <- 0
jake_junis_2019$reward[jake_junis_2019$reward == "0-1"] <- 0
jake_junis_2019$reward[jake_junis_2019$reward == "0-2"] <- 0
jake_junis_2019$reward[jake_junis_2019$reward == "2-1"] <- 0
jake_junis_2019$reward[jake_junis_2019$reward == "2-0"] <- 0
jake_junis_2019$reward[jake_junis_2019$reward == "3-1"] <- 0
jake_junis_2019$reward[jake_junis_2019$reward == "3-0"] <- 0

# adding Xs to batter and swing columns 
jake_junis_2019$batter <- as.character(jake_junis_2019$batter)

jake_junis_2019 <- jake_junis_2019 %>%
  select(at_bat, state, action, 
         next_state, reward, 
         batter, swing) %>%
  mutate(batter = ifelse(reward == "X", "X", batter), 
         swing = ifelse(reward == "X", "X", swing))

# removing all X's 'swing' column 
swing_column_2019 <- jake_junis_2019 %>%
  select(swing) %>%
  filter(swing != "X")

# removing all X's 'batter' column 
batter_column_2019 <- jake_junis_2019 %>%
  select(batter) %>%
  filter(batter != "X")

# removing all X's 'state' column 
state_column_2019 <- jake_junis_2019 %>%
  select(state) %>%
  filter(state != "X")

# removing all X's 'next_state' column 
next_state_column_2019 <- jake_junis_2019 %>%
  select(next_state) %>%
  filter(next_state != "X")

# removing all X's 'reward' column 
reward_column_2019 <- jake_junis_2019 %>%
  select(reward) %>%
  filter(reward != "X")

# action column 
action_column_2019 <- jake_junis_2019 %>%
  select(reward, action) %>%
  filter(reward != "X") %>%
  select(action)

# binding these columns to make final dataset 
jake_junis_2019 <- data.frame(cbind(state_column_2019$state,
                                          action_column_2019$action, 
                                          next_state_column_2019$next_state,
                                          reward_column_2019$reward, 
                                    batter_column_2019$batter, 
                                    swing_column_2019$swing))


# renaming columns 
names(jake_junis_2019)[1] <- "state"
names(jake_junis_2019)[2] <- "action"
names(jake_junis_2019)[3] <- "next_state"
names(jake_junis_2019)[4] <- "reward"
names(jake_junis_2019)[5] <- "batter"
names(jake_junis_2019)[6] <- "swing"



```

Applying Policy to 2019 Data
```{r}

# policy table
pitching_strategy <- data.frame(action = c("SI", "SL", "SI", "SL", "CU", "SI",
                      "SI", "CH", "SL", "CU", "CH", "SI"), 
           count = c('1-0', '1-1',  '1-2', '0-0',  '0-1',  '0-2',
                     '3-0', '3-1',  '3-2',  '2-0',  '2-1',  '2-2')) %>%
  arrange(count)

# optimal action for the 2019 dataset 
jake_junis_2019$state <- as.character(jake_junis_2019$state)
jake_junis_2019$OptimalAction <- predict(junis.model, jake_junis_2019$state)  

# actual pitch distribution  
jake_junis_2019 %>%
  count(action)

# suggested pitch distribution 
jake_junis_2019 %>%
  count(OptimalAction)


```

Plotting New vs. Old Policies
```{r}

# plotting suggested pitch distribution (2019)
ggthemr("pale", type = "outer")

jake_junis_2019 %>%
  count(OptimalAction, sort = TRUE) %>%
  mutate(n = n/sum(n),
         OptimalAction = fct_reorder(OptimalAction, action)) %>%
  ggplot(aes(OptimalAction, n, fill = OptimalAction)) + 
  geom_col(color="black", size = 0.9) + 
  scale_fill_manual(values=c('brown3', 'forestgreen', 'cornflowerblue', 
                             'darkorange2', 'burlywood1')) +
  labs(title = "Jakob Junis 2019 Suggested Pitch Distribution", 
       x = "Pitches", y = "", fill = "Pitches",
       subtitle = "(new optimal policy)") +
  theme(text=element_text(size=16,  family="DIN Alternate Bold")) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.5)) 

# plotting actual pitch distribution (2019)
jake_junis_2019 %>%
  na.omit() %>%
  count(action, sort = TRUE) %>%
  mutate(n = n/sum(n),
         action = fct_reorder(action, -n)) %>%
  ggplot(aes(action, n, fill = action)) + 
  geom_col(color="black", size = 0.9) + 
  scale_fill_manual(values=c('brown3', 'burlywood1', 'forestgreen', 
                            'darkorange2', 'cornflowerblue')) +
  labs(title = "Jakob Junis 2019 Pitch Distribution", 
       subtitle = "(actual)",
       x = "Pitches", y = "", 
       fill = "Pitches") +
  guides(guide_legend(reverse = F)) +  
  theme(text=element_text(size=16,  family="DIN Alternate Bold")) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.5)) 

```

